# Generated by Django 3.1 on 2021-02-23 01:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='number_in_stock',
            field=models.IntegerField(),
            preserve_default=False,
        ),
    ]
